version: '3.8'
name: phish-be
services:
  postgres:
    container_name: postgres-phish
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phishdb
    volumes:
      - ~/db/pgdata:/var/lib/data
    restart: always
    ports:
      - '5432:5432'

  redis:
    container_name: redis-phish
    image: redis
    env_file: .env
    command: redis-server --requirepass ${REDIS_PW}
    restart: always
    ports:
      - '6379:6379'
